const codeInternalErrors = {

  PROCESS_NOT_FINISHED: 55,
  PROCESS_NOT_FINISHED_MESSAGE: "Process not finished",

  UNAUTHORIZED: 401,
  UNAUTHORIZED_MESSAGE: "Unauthorized access",

  USER_ALREADY_EXISTS: 40,
  USER_ALREADY_EXISTS_MESSAGE: "User already exists",

  USER_NO_FOUND: 41,
  USER_NO_FOUND_MESSAGE: "User no found",

  VALIDATION_FAILED: 422,
  VALIDATION_FAILED_MESSAGE: "Invalid request data",
};

export default codeInternalErrors;
